echo " Aku rindu kamu "
echo " aku sayang kamu "
echo " ini aku "
figlet " //////////////////////////////////// "
figlet " \\\\\\\\\\\\\\\\\\\\\\\\\\\\ "
echo " aku sayang kamu "
echo " sarang heoooooooo " 
echo " wkwkwkwkwkwkwk "
echo " lu ngelawakk cuk "